In [77]:
# For folder processing
from scipy.io import loadmat
import os
import tarfile
import urllib.request


# For Image Processing and Display
from PIL import Image
from matplotlib import pyplot as plt
%matplotlib inline 
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets


In [78]:
def retrieve_dataset(url, target_folder):
    """
    Function:
        - Creates a subdirectory "./Data" in the current working directory if it doesn't exist already
        - Downloads the dataset into the newly created folder
        
    Arguments:
        - url: (str) URL of dataset
        - target_folder: (str) relative path of target folder
        
    Return:
        - A "./Data" folder containing the zipped dataset
    """
    # Path to downloaded file
    target_file = target_folder + "/" + url.split("/")[-1]
    
    # If the dataset has already been downloaded, terminate function
    if os.path.exists(target_file):
        print("Data has already been downloaded at '{}'.".format(target_file))
        return
    
    # If target folder doesn't exist yet, create it
    if not os.path.exists(target_folder):
        os.mkdir(target_folder.split("/")[-1])
        print("Created a new folder at '{}'.".format(target_folder))
        
    # Downloading the dataset
    print("Downloading dataset from '{}', please wait...".format(url))
    urllib.request.urlretrieve(url, target_file)  
    print("File successfully downloaded to '{}''.".format(path))

In [79]:
url_1 = "http://imagenet.stanford.edu/internal/car196/cars_train.tgz"
url_2 = 
target_folder = "./Data"

SyntaxError: invalid syntax (<ipython-input-79-1234c5445382>, line 2)

In [80]:
def show_image(dataset, index):
    """
    Function:
        - shows an image from the dataset and its label
    Arguments:
        - dataset (list): list of tuples: (nd.array of original image, nd.array of preprocessed image, image name, image label)
    Returns:
         none, but the function will show the original and preprocessedimage, its name and its label
    """
    
    fig, [ax1, ax2] = plt.subplots(nrows=1, ncols=2, figsize=(9,5))
    ax1.imshow(dataset[index][0], interpolation='nearest')
    ax1.set_title("Your original image after resizing:")
    ax2.imshow(dataset[index][1], interpolation='nearest')
    ax2.set_title("Preprocessed image as model input:")
    plt.show()
    print(f"Image title: {dataset[index][2]}")
    print(f"Image class: {dataset[index][3]}")

In [48]:
x = loadmat('devkit/cars_meta.mat')

In [64]:
Class_id = {int(index+1):class_name[0] for index, class_name in enumerate(x["class_names"][0])}

In [65]:
Class_id

{1: 'AM General Hummer SUV 2000',
 2: 'Acura RL Sedan 2012',
 3: 'Acura TL Sedan 2012',
 4: 'Acura TL Type-S 2008',
 5: 'Acura TSX Sedan 2012',
 6: 'Acura Integra Type R 2001',
 7: 'Acura ZDX Hatchback 2012',
 8: 'Aston Martin V8 Vantage Convertible 2012',
 9: 'Aston Martin V8 Vantage Coupe 2012',
 10: 'Aston Martin Virage Convertible 2012',
 11: 'Aston Martin Virage Coupe 2012',
 12: 'Audi RS 4 Convertible 2008',
 13: 'Audi A5 Coupe 2012',
 14: 'Audi TTS Coupe 2012',
 15: 'Audi R8 Coupe 2012',
 16: 'Audi V8 Sedan 1994',
 17: 'Audi 100 Sedan 1994',
 18: 'Audi 100 Wagon 1994',
 19: 'Audi TT Hatchback 2011',
 20: 'Audi S6 Sedan 2011',
 21: 'Audi S5 Convertible 2012',
 22: 'Audi S5 Coupe 2012',
 23: 'Audi S4 Sedan 2012',
 24: 'Audi S4 Sedan 2007',
 25: 'Audi TT RS Coupe 2012',
 26: 'BMW ActiveHybrid 5 Sedan 2012',
 27: 'BMW 1 Series Convertible 2012',
 28: 'BMW 1 Series Coupe 2012',
 29: 'BMW 3 Series Sedan 2012',
 30: 'BMW 3 Series Wagon 2012',
 31: 'BMW 6 Series Convertible 2007',
 32: 

In [18]:
b = loadmat('devkit/cars_train_annos.mat')

In [ ]:
# Annotations = {"fname": {"bbox_xmin": 12, "bbox_xmax": 13, "bbox_y1": , "bbox_y2"}}

In [31]:
Annotations = {}

In [66]:
b["annotations"][0]

array([(array([[39]], dtype=uint8), array([[116]], dtype=uint8), array([[569]], dtype=uint16), array([[375]], dtype=uint16), array([[14]], dtype=uint8), array(['00001.jpg'], dtype='<U9')),
       (array([[36]], dtype=uint8), array([[116]], dtype=uint8), array([[868]], dtype=uint16), array([[587]], dtype=uint16), array([[3]], dtype=uint8), array(['00002.jpg'], dtype='<U9')),
       (array([[85]], dtype=uint8), array([[109]], dtype=uint8), array([[601]], dtype=uint16), array([[381]], dtype=uint16), array([[91]], dtype=uint8), array(['00003.jpg'], dtype='<U9')),
       ...,
       (array([[26]], dtype=uint8), array([[246]], dtype=uint8), array([[660]], dtype=uint16), array([[449]], dtype=uint16), array([[163]], dtype=uint8), array(['08142.jpg'], dtype='<U9')),
       (array([[78]], dtype=uint8), array([[526]], dtype=uint16), array([[1489]], dtype=uint16), array([[908]], dtype=uint16), array([[112]], dtype=uint8), array(['08143.jpg'], dtype='<U9')),
       (array([[20]], dtype=uint8), arra

In [67]:
b["annotations"][0][0][5][0]

'00001.jpg'

In [69]:
Annotations = {image[5][0]:{"bbox_xmin": image[0][0][0], "bbox_xmin": image[0][0][0], "bbox_xmax": image[1][0][0],"bbox_ymin": image[2][0][0],"bbox_ymax": image[3][0][0],"class_number": image[4][0][0], "class_name": Class_id[image[4][0][0]]} for image in b["annotations"][0]}

In [70]:
Annotations

{'00001.jpg': {'bbox_xmin': 39,
  'bbox_xmax': 116,
  'bbox_ymin': 569,
  'bbox_ymax': 375,
  'class_number': 14,
  'class_name': 'Audi TTS Coupe 2012'},
 '00002.jpg': {'bbox_xmin': 36,
  'bbox_xmax': 116,
  'bbox_ymin': 868,
  'bbox_ymax': 587,
  'class_number': 3,
  'class_name': 'Acura TL Sedan 2012'},
 '00003.jpg': {'bbox_xmin': 85,
  'bbox_xmax': 109,
  'bbox_ymin': 601,
  'bbox_ymax': 381,
  'class_number': 91,
  'class_name': 'Dodge Dakota Club Cab 2007'},
 '00004.jpg': {'bbox_xmin': 621,
  'bbox_xmax': 393,
  'bbox_ymin': 1484,
  'bbox_ymax': 1096,
  'class_number': 134,
  'class_name': 'Hyundai Sonata Hybrid Sedan 2012'},
 '00005.jpg': {'bbox_xmin': 14,
  'bbox_xmax': 36,
  'bbox_ymin': 133,
  'bbox_ymax': 99,
  'class_number': 106,
  'class_name': 'Ford F-450 Super Duty Crew Cab 2012'},
 '00006.jpg': {'bbox_xmin': 259,
  'bbox_xmax': 289,
  'bbox_ymin': 515,
  'bbox_ymax': 416,
  'class_number': 123,
  'class_name': 'Geo Metro Convertible 1993'},
 '00007.jpg': {'bbox_xmin': 8

In [89]:
def load_image(Annotations = Annotations):
    """
    Function: 
        -loads images from the target folder
        -resizes and preprocesses the images 
        -append the original and preprocssed images, file names and labels into a "dataset"
    Arguments: 
        -folder (str): the directory containing the images
        -label (str): the class of images
        -width (int): desired width after resizing
        -height (int): desired height after resizing
    Returns: 
        -dataset (list): list of tuples: (nd.array of original image, nd.array of preprocessed image, image name, image label)
    """
    image_folder = "./cars_train"
    

    
    for filename in os.listdir(image_folder):
        with open(os.path.join(image_folder,filename)) as i:
            img = Image.open(i)
            img_np = np.array(img)
            Annotations[filename]["image"] = img_np
    return Annotations


In [104]:
def loadImages(path):
    imagesList = os.listdir(path)
    loadedImages = []
    for index, image in enumerate(imagesList):
        with open(os.path.join(path, image), 'rb') as i:
            img = Image.open(i)
            loadedImages.append(img)
        if index == 5:
            break
    return loadedImages

In [105]:
image_folder = "./cars_train"

In [107]:
imagesList = os.listdir(image_folder)

OSError: [Errno 24] Too many open files: './cars_train'

In [17]:
def show_image(dataset, index):
    """
    Function:
        - shows an image from the dataset and its label
    Arguments:
        - dataset (list): list of tuples: (nd.array of original image, nd.array of preprocessed image, image name, image label)
    Returns:
         none, but the function will show the original and preprocessedimage, its name and its label
    """
    image_folder = "./cars_train"
    
    for filename in os.listdir(folder):
        img = Image.open(os.path.join(folder,filename))
        if img is not None:
            # Resize the image
            img = img.resize((224, 224))
            
            # Convert it into np array
            img_np = np.array(img)
            
                          
                          
            fig, [ax1, ax2] = plt.subplots(nrows=1, ncols=2, figsize=(9,5))
            ax1.imshow(dataset[index][0], interpolation='nearest')
            ax1.set_title("Your original image after resizing:")
            ax2.imshow(dataset[index][1], interpolation='nearest')
            ax2.set_title("Preprocessed image as model input:")
            plt.show()
            print(f"Image title: {dataset[index][2]}")
            print(f"Image class: {dataset[index][3]}")